// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionInp': string;
  'add': string;
  'addTo': string;
  'button': string;
  'card': string;
  'card_price': string;
  'cart_count': string;
  'code': string;
  'column': string;
  'description': string;
  'icon': string;
  'image': string;
  'info': string;
  'numberInput': string;
  'price': string;
  'prices': string;
  'properties': string;
  'root': string;
  'shipping': string;
  'sum': string;
  'toCart': string;
}
export const cssExports: CssExports;
export default cssExports;
