// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'five': string;
  'logo': string;
  'menu_icon': string;
  'menu_item': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
