// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'burg': string;
  'coin': string;
  'droplink': string;
  'head_controls': string;
  'header': string;
}
export const cssExports: CssExports;
export default cssExports;
