// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bigdroplink': string;
  'coin': string;
  'small': string;
  'smalldroplink': string;
  'sum': string;
}
export const cssExports: CssExports;
export default cssExports;
